[project]
name = "sitemap"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "memray>=1.18.0",
    "scrapy",
]

[tool.uv.sources]
scrapy = { git = "https://github.com/abebus/scrapy.git", rev = "sitemap" }
